### ISSUE TITLE
Flickering in song select

### ISSUE THREAD

**Issue by yaanae** [Tejune/Project-Ripple#18]
When moving between songs the background flickers. It's easiest to see when moving between two difficulties of the same song. This is especially hard on the eyes when navigating with a keyboard.

Maybe the screen quickly turns black and only after that re-renders the image? Since it's barely noticeable between different songs, and maybe even desirable, Project-Ripple should not reload the image when moving between difficulties, just like how the music doesn't reload.

**Comment by Tejune** [comment]
No longer happens when switching between difficulties of the same song :)
